package slogger

const (
	// --- 1. Basic HTTP and Tracing ---

	// KeyRequestID represents the unique identifier for the HTTP request (e.g., UUID).
	KeyRequestID = "request_id"

	// KeyDuration denotes the execution time of the request in milliseconds.
	KeyDuration = "duration_ms"

	// KeyMethod specifies the HTTP method used (GET, POST, etc.).
	KeyMethod = "http_method"

	// KeyHost contains the target host of the HTTP request.
	KeyHost = "http_host"

	// KeyPort represents the target port of the HTTP request.
	KeyPort = "http_port"

	// KeyPath specifies the URL path of the HTTP request.
	KeyPath = "http_path"

	// KeyStatusCode indicates the HTTP response status code (e.g., 200, 500).
	KeyStatusCode = "status_code"

	// KeyError provides detailed error messages or stack traces.
	KeyError = "error_details"

	// KeyClientIP holds the IP address of the client making the request.
	KeyClientIP = "client_ip"

	// KeyUserAgent contains the User-Agent header from the client.
	KeyUserAgent = "user_agent"

	// --- 2. Identification and B2G (Multi-tenancy) ---

	// KeyUserID represents the unique identifier of the authenticated user.
	KeyUserID = "user_id"

	// KeyRole denotes the access role of the user (e.g., student, teacher, admin).
	KeyRole = "user_role"

	// KeySchoolID specifies the tenant ID representing the school or municipality.
	KeySchoolID = "school_id"

	// KeyClassID corresponds to the identifier of the specific class or group.
	KeyClassID = "class_id"

	// KeyDeviceID represents the identifier for the user's device (used for push notifications/tracking).
	KeyDeviceID = "device_id"

	// --- 3. Sensitive Data (PII & Secrets) - STRICTLY FOR REDACTION ---

	// KeyEmail corresponds to the user's email address (must be redacted).
	KeyEmail = "user_email"

	// KeyPassword denotes the user's plain text or hashed password (must be redacted).
	KeyPassword = "password"

	// KeyToken contains JWT or refresh tokens (must be redacted).
	KeyToken = "token"

	// KeyAPIKey represents third-party API keys (must be redacted).
	KeyAPIKey = "api_key"

	// --- 4. Behavioral Telemetry (ClickHouse / FSRS) ---

	// KeySessionID represents the identifier for the current learning session.
	KeySessionID = "session_id"

	// KeyEventType denotes the type of telemetry event (e.g., "card_view", "lesson_complete").
	KeyEventType = "event_type"

	// KeyWordID identifies the vocabulary word being studied.
	KeyWordID = "word_id"

	// KeyProfileID represents the active language learning profile ID.
	KeyProfileID = "profile_id"

	// KeyClickedHint indicates whether the user clicked the AI hint button.
	KeyClickedHint = "clicked_hint"

	// KeyDifficulty specifies the current FSRS difficulty index of the flashcard.
	KeyDifficulty = "difficulty_index"

	// KeySourceLang denotes the user's native/source language code (e.g., "en").
	KeySourceLang = "source_lang"

	// KeyTargetLang denotes the language code being learned (e.g., "no").
	KeyTargetLang = "target_lang"

	// --- 5. AI Router & FinOps (AI Cost Control) ---

	// KeyAIModel specifies the name of the AI model used (e.g., "gemini-1.5-flash", "deepl-pro").
	KeyAIModel = "ai_model"

	// KeyAITask represents the purpose of the AI request (e.g., "generate_lesson", "grammar_check").
	KeyAITask = "ai_task"

	// KeyPromptTokens indicates the number of input tokens sent to the LLM (for billing).
	KeyPromptTokens = "prompt_tokens"

	// KeyCompTokens signifies the number of output tokens generated by the LLM (for billing).
	KeyCompTokens = "completion_tokens"

	// KeyAILatency tracks the API response time in milliseconds.
	KeyAILatency = "ai_latency_ms"

	// KeyAICacheHit indicates whether the AI response was served from cache.
	KeyAICacheHit = "ai_cache_hit"

	// KeyDegradation tracks whether a fallback was triggered due to AI failure (e.g., 503).
	KeyDegradation = "graceful_fallback"

	// --- 6. Background Tasks & Caching (Redis / Asynq) ---

	// KeyWorkerTask stores the name of the Asynq background job being executed.
	KeyWorkerTask = "worker_task"

	// KeyQueue denotes the name of the queue processing the task.
	KeyQueue = "queue_name"

	// KeyAttempt tracks the number of retries attempted for the background task.
	KeyAttempt = "retry_attempt"

	// KeyCacheKey specifies the specific key used for Redis cache lookup.
	KeyCacheKey = "cache_key"

	// KeyCacheHit tracks a general cache hit/miss status.
	KeyCacheHit = "cache_hit"
)
