version: 2

run:
  # Таймаут, чтобы линтер не отваливался на больших проектах
  timeout: 5m

linters-settings:
  govet:
    # Включаем проверку на "затенение" переменных (когда локальная переменная перекрывает внешнюю)
    enable:
      - shadow
  gocyclo:
    # Ограничиваем цикломатическую сложность функций (чтобы они не были огромными)
    min-complexity: 15

linters:
  disable-all: true
  enable:
    - govet      # Стандартный линтер Go (находит подозрительные конструкции)
    - errcheck   # Проверяет, что мы не игнорируем ошибки
    - staticcheck # Продвинутый анализатор (ищет баги, устаревшие функции)
    - ineffassign # Ищет переменные, которым присвоили значение, но не использовали
    - gocyclo    # Следит за сложностью функций