version = 5.4.0
archive_dir = /etc/letsencrypt/archive/wordsgo.tolmachov.dev
cert = /etc/letsencrypt/live/wordsgo.tolmachov.dev/cert.pem
privkey = /etc/letsencrypt/live/wordsgo.tolmachov.dev/privkey.pem
chain = /etc/letsencrypt/live/wordsgo.tolmachov.dev/chain.pem
fullchain = /etc/letsencrypt/live/wordsgo.tolmachov.dev/fullchain.pem
[renewalparams]
account = 6b8411c4e390cf41035b43c3f6087d17
authenticator = webroot
webroot_path = /var/www/certbot,
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[[webroot_map]]
wordsgo.tolmachov.dev = /var/www/certbot
