export const languages: Record<string, string> = {
  "ACE": "Acehnese",
  "AF": "Afrikaans",
  "AN": "Aragonese",
  "AR": "Arabic",
  "AS": "Assamese",
  "AY": "Aymara",
  "AZ": "Azerbaijani",
  "BA": "Bashkir",
  "BE": "Belarusian",
  "BG": "Bulgarian",
  "BHO": "Bhojpuri",
  "BN": "Bengali",
  "BR": "Breton",
  "BS": "Bosnian",
  "CA": "Catalan",
  "CEB": "Cebuano",
  "CKB": "Kurdish (Sorani)",
  "CS": "Czech",
  "CY": "Welsh",
  "DA": "Danish",
  "DE": "German",
  "EL": "Greek",
  "EN": "English",
  "EN-GB": "English (British)",
  "EN-US": "English (American)",
  "EO": "Esperanto",
  "ES": "Spanish",
  "ES-419": "Spanish (Latin American)",
  "ET": "Estonian",
  "EU": "Basque",
  "FA": "Persian",
  "FI": "Finnish",
  "FR": "French",
  "GA": "Irish",
  "GL": "Galician",
  "GN": "Guarani",
  "GOM": "Konkani",
  "GU": "Gujarati",
  "HA": "Hausa",
  "HE": "Hebrew",
  "HI": "Hindi",
  "HR": "Croatian",
  "HT": "Haitian Creole",
  "HU": "Hungarian",
  "HY": "Armenian",
  "ID": "Indonesian",
  "IG": "Igbo",
  "IS": "Icelandic",
  "IT": "Italian",
  "JA": "Japanese",
  "JV": "Javanese",
  "KA": "Georgian",
  "KK": "Kazakh",
  "KMR": "Kurdish (Kurmanji)",
  "KO": "Korean",
  "KY": "Kyrgyz",
  "LA": "Latin",
  "LB": "Luxembourgish",
  "LMO": "Lombard",
  "LN": "Lingala",
  "LT": "Lithuanian",
  "LV": "Latvian",
  "MAI": "Maithili",
  "MG": "Malagasy",
  "MI": "Maori",
  "MK": "Macedian",
  "ML": "Malayalam",
  "MN": "Mongolian",
  "MR": "Marathi",
  "MS": "Malay",
  "MT": "Maltese",
  "MY": "Burmese",
  "NB": "Norwegian Bokmål",
  "NE": "Nepali",
  "NL": "Dutch",
  "OC": "Occitan",
  "OM": "Oromo",
  "PA": "Punjabi",
  "PAG": "Pangasinan",
  "PAM": "Kapampangan",
  "PL": "Polish",
  "PRS": "Dari",
  "PS": "Pashto",
  "PT": "Portuguese",
  "PT-BR": "Portuguese (Brazilian)",
  "PT-PT": "Portuguese (excluding Brazilian)",
  "QU": "Quechua",
  "RO": "Romanian",
  "RU": "Russian",
  "SA": "Sanskrit",
  "SCN": "Sicilian",
  "SK": "Slovak",
  "SL": "Slovenian",
  "SQ": "Albanian",
  "SR": "Serbian",
  "ST": "Sesotho",
  "SU": "Sundanese",
  "SV": "Swedish",
  "SW": "Swahili",
  "TA": "Tamil",
  "TE": "Telugu",
  "TG": "Tajik",
  "TH": "Thai",
  "TK": "Turkmen",
  "TL": "Tagalog",
  "TN": "Tswana",
  "TR": "Turkish",
  "TS": "Tsonga",
  "TT": "Tatar",
  "UK": "Ukrainian",
  "UR": "Urdu",
  "UZ": "Uzbek",
  "VI": "Vietnamese",
  "WO": "Wolof",
  "XH": "Xhosa",
  "YI": "Yiddish",
  "YUE": "Cantonese",
  "ZH": "Chinese",
  "ZH-HANS": "Chinese (simplified)",
  "ZH-HANT": "Chinese (traditional)",
  "ZU": "Zulu",
};

export function getLanguageName(code: string): string {
  if (!code) return '';
  return languages[code.toUpperCase()] || code;
}
