// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/lesson/check": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Submits an answer for the current word and returns the next word",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "lesson"
                ],
                "summary": "Check the answer for a word",
                "parameters": [
                    {
                        "description": "Answer data",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.AnswerReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.CheckAnswerResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request body",
                        "schema": {
                            "$ref": "#/definitions/handler.JSONError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handler.JSONError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/handler.JSONError"
                        }
                    }
                }
            }
        },
        "/lesson/finish": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Clears the current lesson state from the cache for the current user",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "lesson"
                ],
                "summary": "Finish the learning lesson",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handler.JSONError"
                        }
                    }
                }
            }
        },
        "/lesson/start": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Gets the next word for the user to learn",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "lesson"
                ],
                "summary": "Start a learning lesson",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.StartLessonResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handler.JSONError"
                        }
                    },
                    "404": {
                        "description": "no_words_for_lesson",
                        "schema": {
                            "$ref": "#/definitions/handler.JSONError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/handler.JSONError"
                        }
                    }
                }
            }
        },
        "/login": {
            "post": {
                "description": "Login and get JWT token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "User Login",
                "parameters": [
                    {
                        "description": "Login credentials",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.LoginResponse"
                        }
                    },
                    "401": {
                        "description": "Invalid credentials",
                        "schema": {
                            "$ref": "#/definitions/handler.JSONError"
                        }
                    }
                }
            }
        },
        "/playlists": {
            "get": {
                "description": "Returns a list of all playlists (collections of public word lists)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "words"
                ],
                "summary": "Get playlists",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/modelsDB.Playlist"
                            }
                        }
                    }
                }
            }
        },
        "/playlists/{id}": {
            "get": {
                "description": "Returns detailed information about a playlist, including all its public word lists",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "words"
                ],
                "summary": "Get playlist by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Playlist ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/modelsDB.PlaylistDetail"
                        }
                    }
                }
            }
        },
        "/practice/checkAnswerPractice": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Submits user translations for the generated sentences and returns AI feedback",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AI Practice"
                ],
                "summary": "Check AI practice answer",
                "parameters": [
                    {
                        "description": "User translations",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.UserTranslateResponse"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/gemini.CheckAnswerPracticeWithGeminiResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.JSONError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handler.JSONError"
                        }
                    },
                    "429": {
                        "description": "Too Many Requests",
                        "schema": {
                            "$ref": "#/definitions/handler.JSONError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.JSONError"
                        }
                    }
                }
            }
        },
        "/practice/finishPractice": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Clears the AI practice session from the cache",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AI Practice"
                ],
                "summary": "Finish AI practice",
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handler.JSONError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.JSONError"
                        }
                    }
                }
            }
        },
        "/practice/startPractice": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Generates a set of contextual sentences for translation based on a topic using Gemini AI",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AI Practice"
                ],
                "summary": "Start AI practice",
                "parameters": [
                    {
                        "description": "Topic for practice",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/gemini.StartPracticeWithGeminiResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.JSONError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handler.JSONError"
                        }
                    },
                    "429": {
                        "description": "Too Many Requests",
                        "schema": {
                            "$ref": "#/definitions/handler.JSONError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.JSONError"
                        }
                    }
                }
            }
        },
        "/public-lists": {
            "get": {
                "description": "Returns a list of all public word lists, optionally filtered by language",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "words"
                ],
                "summary": "Get public word lists",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Source language code (e.g., 'en')",
                        "name": "source_lang",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Target language code (e.g., 'ru')",
                        "name": "target_lang",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Proficiency level (e.g., 'A1')",
                        "name": "level",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/modelsDB.PublicWordList"
                            }
                        }
                    }
                }
            }
        },
        "/public-lists/{id}": {
            "get": {
                "description": "Returns detailed information about a public word list, including all its words",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "words"
                ],
                "summary": "Get public word list by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Word list ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/modelsDB.PublicWordListDetail"
                        }
                    }
                }
            }
        },
        "/users": {
            "get": {
                "description": "Get list of all users from DB",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Get list of users",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Limit records per page (default 10)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page number (default 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Sort order: asc or desc (default desc)",
                        "name": "order",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.ListOfUsersResponse"
                        }
                    },
                    "500": {
                        "description": "Failed to get users",
                        "schema": {
                            "$ref": "#/definitions/handler.JSONError"
                        }
                    }
                }
            },
            "post": {
                "description": "Register a new user in the system",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Create a new user",
                "parameters": [
                    {
                        "description": "User registration info",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.CreateUserRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.UserResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid input or validation info",
                        "schema": {
                            "$ref": "#/definitions/handler.JSONError"
                        }
                    },
                    "409": {
                        "description": "User already exists",
                        "schema": {
                            "$ref": "#/definitions/handler.JSONError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/handler.JSONError"
                        }
                    }
                }
            }
        },
        "/users/lang": {
            "get": {
                "description": "Returns a list of supported source and target languages for learning and translation",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Get available languages",
                "responses": {
                    "200": {
                        "description": "Successfully retrieved languages",
                        "schema": {
                            "$ref": "#/definitions/models.LangResponse"
                        }
                    }
                }
            }
        },
        "/users/{id}": {
            "get": {
                "description": "Get User By Slug from DB",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Get user by Slug",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "User UUID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.UserResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid UUID",
                        "schema": {
                            "$ref": "#/definitions/handler.JSONError"
                        }
                    },
                    "404": {
                        "description": "User not found",
                        "schema": {
                            "$ref": "#/definitions/handler.JSONError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/handler.JSONError"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Update user information by its UUID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Update user by Slug",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "User UUID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "User update info",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.UpdateUserRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully updated",
                        "schema": {
                            "$ref": "#/definitions/models.UserResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid user Slug",
                        "schema": {
                            "$ref": "#/definitions/handler.JSONError"
                        }
                    },
                    "403": {
                        "description": "Permission denied",
                        "schema": {
                            "$ref": "#/definitions/handler.JSONError"
                        }
                    },
                    "500": {
                        "description": "Failed to update user",
                        "schema": {
                            "$ref": "#/definitions/handler.JSONError"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Delete user by Slug from DB",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Delete user by Slug",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "User UUID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Invalid user Slug",
                        "schema": {
                            "$ref": "#/definitions/handler.JSONError"
                        }
                    },
                    "403": {
                        "description": "You can delete only your own account",
                        "schema": {
                            "$ref": "#/definitions/handler.JSONError"
                        }
                    },
                    "500": {
                        "description": "Failed to delete user",
                        "schema": {
                            "$ref": "#/definitions/handler.JSONError"
                        }
                    }
                }
            }
        },
        "/words/GetMe": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns language settings and total correct answers for the current user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "words"
                ],
                "summary": "Get current user info",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.GetMeResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handler.JSONError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/handler.JSONError"
                        }
                    }
                }
            }
        },
        "/words/create": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Adds a new word to the user's dictionary",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "words"
                ],
                "summary": "Create a new word",
                "parameters": [
                    {
                        "description": "Word data",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.CreateReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Response"
                        }
                    },
                    "400": {
                        "description": "Invalid request body",
                        "schema": {
                            "$ref": "#/definitions/handler.JSONError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handler.JSONError"
                        }
                    },
                    "408": {
                        "description": "Database timeout",
                        "schema": {
                            "$ref": "#/definitions/handler.JSONError"
                        }
                    },
                    "409": {
                        "description": "Word already exists",
                        "schema": {
                            "$ref": "#/definitions/handler.JSONError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/handler.JSONError"
                        }
                    }
                }
            }
        },
        "/words/create-batch": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Adds multiple words (up to 500) to the user's dictionary in a single request",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "words"
                ],
                "summary": "Batch save words",
                "parameters": [
                    {
                        "description": "Batch of words to save",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.CreateBatchReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.JSONError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handler.JSONError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.JSONError"
                        }
                    }
                }
            }
        },
        "/words/import": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Uploads and processes a CSV or JSON file to add multiple words to the user's dictionary",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "words"
                ],
                "summary": "Import words",
                "parameters": [
                    {
                        "type": "file",
                        "description": "CSV or JSON file with words",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.JSONError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handler.JSONError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.JSONError"
                        }
                    }
                }
            }
        },
        "/words/translate": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Translates a word using DeepL API",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "words"
                ],
                "summary": "Translate a word",
                "parameters": [
                    {
                        "description": "Translation request data",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.TranslateReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.TranslateResp"
                        }
                    },
                    "400": {
                        "description": "Invalid request body",
                        "schema": {
                            "$ref": "#/definitions/handler.JSONError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handler.JSONError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/handler.JSONError"
                        }
                    }
                }
            }
        },
        "/words/wordInfo": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns detailed explanation, grammar, and usage examples for a word using Gemini AI",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "words"
                ],
                "summary": "Get word details using AI",
                "parameters": [
                    {
                        "description": "Data for Gemini AI prompt",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/gemini.WordInfoRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully generated explanation",
                        "schema": {
                            "$ref": "#/definitions/gemini.WordInfoResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request body",
                        "schema": {
                            "$ref": "#/definitions/handler.JSONError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handler.JSONError"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/handler.JSONError"
                        }
                    }
                }
            }
        },
        "/words/wordList": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns a list of thematic words based on user request or predefined topic using Gemini AI",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AI Features"
                ],
                "summary": "Generate word list",
                "parameters": [
                    {
                        "description": "Topic and request for word list generation",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.WordListReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.WordListResp"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.JSONError"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handler.JSONError"
                        }
                    },
                    "429": {
                        "description": "Too Many Requests",
                        "schema": {
                            "$ref": "#/definitions/handler.JSONError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.JSONError"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "gemini.CheckAnswerPracticeWithGeminiResponse": {
            "type": "object",
            "properties": {
                "general_comment": {
                    "type": "string"
                },
                "results": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/gemini.PracticeWithGeminiResult"
                    }
                }
            }
        },
        "gemini.PracticeWithGeminiResult": {
            "type": "object",
            "properties": {
                "ideal_translation": {
                    "type": "string"
                },
                "sentence_number": {
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                },
                "status_localized": {
                    "type": "string"
                },
                "teacher_comment": {
                    "type": "string"
                },
                "your_version": {
                    "type": "string"
                }
            }
        },
        "gemini.StartPracticeWithGeminiResponse": {
            "type": "object",
            "properties": {
                "level": {
                    "type": "string"
                },
                "sentences": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "gemini.WordInfoRequest": {
            "type": "object",
            "properties": {
                "source_lang": {
                    "type": "string"
                },
                "source_word": {
                    "type": "string"
                },
                "target_lang": {
                    "type": "string"
                },
                "target_word": {
                    "type": "string"
                }
            }
        },
        "gemini.WordInfoResponse": {
            "type": "object",
            "properties": {
                "response": {
                    "type": "string"
                }
            }
        },
        "handler.JSONError": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "models.AnswerReq": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "target_word": {
                    "type": "string"
                }
            }
        },
        "models.CheckAnswerResponse": {
            "type": "object",
            "properties": {
                "is_correct": {
                    "type": "boolean"
                },
                "next_word": {
                    "$ref": "#/definitions/models.Response"
                },
                "total_correct": {
                    "type": "integer"
                }
            }
        },
        "models.CreateBatchReq": {
            "type": "object",
            "properties": {
                "source_lang": {
                    "type": "string"
                },
                "target_lang": {
                    "type": "string"
                },
                "words": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.WordListResp"
                    }
                }
            }
        },
        "models.CreateReq": {
            "type": "object",
            "properties": {
                "comment": {
                    "type": "string"
                },
                "source_lang": {
                    "type": "string"
                },
                "source_word": {
                    "type": "string"
                },
                "target_lang": {
                    "type": "string"
                },
                "target_word": {
                    "type": "string"
                }
            }
        },
        "models.CreateUserRequest": {
            "type": "object",
            "required": [
                "email",
                "first_name",
                "last_name",
                "password",
                "source_lang",
                "target_lang"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "example": "test@user.com"
                },
                "first_name": {
                    "type": "string",
                    "example": "test"
                },
                "last_name": {
                    "type": "string",
                    "example": "user"
                },
                "password": {
                    "type": "string",
                    "minLength": 8,
                    "example": "SecurePass123!"
                },
                "source_lang": {
                    "type": "string",
                    "example": "en"
                },
                "target_lang": {
                    "type": "string",
                    "example": "en"
                }
            }
        },
        "models.GetMeResponse": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "first_name": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "langCodeResp": {
                    "$ref": "#/definitions/models.LangCodeResp"
                },
                "last_name": {
                    "type": "string"
                },
                "source_lang": {
                    "type": "string"
                },
                "totalCorrect": {
                    "type": "integer"
                }
            }
        },
        "models.LangCodeResp": {
            "type": "object",
            "properties": {
                "source": {
                    "type": "string"
                },
                "target": {
                    "type": "string"
                }
            }
        },
        "models.LangItem": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "models.LangResponse": {
            "type": "object",
            "properties": {
                "source": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.LangItem"
                    }
                },
                "target": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.LangItem"
                    }
                }
            }
        },
        "models.ListOfUsersResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.UserResponse"
                    }
                },
                "limit": {
                    "type": "integer"
                },
                "page": {
                    "type": "integer"
                },
                "pages": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "models.LoginRequest": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "example": "test@user.com"
                },
                "password": {
                    "type": "string",
                    "example": "SecurePass123!"
                }
            }
        },
        "models.LoginResponse": {
            "type": "object",
            "properties": {
                "source_lang": {
                    "type": "string"
                },
                "token": {
                    "type": "string"
                }
            }
        },
        "models.Response": {
            "type": "object",
            "properties": {
                "comment": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "source_lang": {
                    "type": "string"
                },
                "source_word": {
                    "type": "string"
                },
                "target_lang": {
                    "type": "string"
                },
                "target_word": {
                    "type": "string"
                }
            }
        },
        "models.StartLessonResponse": {
            "type": "object",
            "properties": {
                "total_correct": {
                    "type": "integer"
                },
                "word": {
                    "$ref": "#/definitions/models.Response"
                }
            }
        },
        "models.TranslateReq": {
            "type": "object",
            "properties": {
                "source_lang": {
                    "type": "string"
                },
                "source_word": {
                    "type": "string"
                },
                "target_lang": {
                    "type": "string"
                },
                "target_word": {
                    "type": "string"
                }
            }
        },
        "models.TranslateResp": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "source_word": {
                    "type": "string"
                },
                "target_word": {
                    "type": "string"
                }
            }
        },
        "models.UpdateUserRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "first_name": {
                    "type": "string"
                },
                "last_name": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                },
                "source_lang": {
                    "type": "string"
                },
                "target_lang": {
                    "type": "string"
                }
            }
        },
        "models.UserResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "first_name": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "last_name": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                },
                "source_lang": {
                    "type": "string"
                },
                "target_lang": {
                    "type": "string"
                },
                "total_correct": {
                    "type": "integer"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "models.UserTranslateResponse": {
            "type": "object",
            "properties": {
                "translation": {
                    "type": "string"
                }
            }
        },
        "models.WordListReq": {
            "type": "object",
            "properties": {
                "level": {
                    "type": "string"
                },
                "source_lang": {
                    "type": "string"
                },
                "target_lang": {
                    "type": "string"
                },
                "topic": {
                    "type": "string"
                },
                "user_topic": {
                    "type": "string"
                }
            }
        },
        "models.WordListResp": {
            "type": "object",
            "properties": {
                "comment": {
                    "type": "string"
                },
                "source_word": {
                    "type": "string"
                },
                "target_word": {
                    "type": "string"
                }
            }
        },
        "modelsDB.Playlist": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "creator_name": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "modelsDB.PlaylistDetail": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "creator_name": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "lists": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/modelsDB.PublicWordList"
                    }
                },
                "title": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "modelsDB.PublicWordList": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "creator_name": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "level": {
                    "type": "string"
                },
                "source_lang": {
                    "type": "string"
                },
                "target_lang": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "modelsDB.PublicWordListDetail": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "creator_name": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/modelsDB.PublicWordListItem"
                    }
                },
                "level": {
                    "type": "string"
                },
                "source_lang": {
                    "type": "string"
                },
                "target_lang": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "modelsDB.PublicWordListItem": {
            "type": "object",
            "properties": {
                "comment": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "list_id": {
                    "type": "string"
                },
                "source_word": {
                    "type": "string"
                },
                "target_word": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.1",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Synaply API",
	Description:      "AI-Powered Language Learning Platform API",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
