name: Deploy to DigitalOcean

# Rule: run this script only on push to the main branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest # The robot will work on Ubuntu

    steps:
      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
        
          # Here is the script that will execute ON YOUR SERVER:
          script: |
            # STOP the script on any error (so GitHub lights up red if something goes wrong)
            set -e
            
            # Go to the project folder
            cd /root/wordsGo_v2
            
            # 1. Download ALL fresh updates from GitHub to the server buffer
            git fetch origin
            
            # 2. HARD reset the code state on the server to an exact copy of the main branch
            git reset --hard origin/main
            
            # Rebuild and restart containers in the background
            docker compose up -d --build
